name: "Terraform Valida Modulo"

on:
  workflow_call:
    inputs:
      os_version:
        description: "Versão do sistema operacional"
        required: false
        default: "ubuntu-20.04"
        type: string
      working_directory:
        description: "Diretório em que a pipeline irá atuar"
        required: false
        default: ""
        type: string

jobs:
  jobs_terraform:
    name: Terraform workflow
    runs-on: ${{ inputs.os_version }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepara variavel
        run: |
         export TF_VERSION=$(sed -nr 's/\s*required_version\s+=\s+"(.*)"/\1/p' *.tf)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: $TF_VERSION

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -diff

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Validação do tfsec
        id: tfsec
        run: |
          docker run --rm -v $PWD:/app -w /app tfsec/tfsec .
