name: Testes para pipeline Terraform

on:
  push:

jobs:
  test-terraform:
    uses: "./.github/workflows/terraform_valida_modulo.yaml"
    strategy:
      matrix:
        working-dir:
          - tests/terraform/test-001
          - tests/terraform/test-002
          - tests/terraform/test-003
          - tests/terraform/test-004
    with:
      working_directory: ${{ matrix.working-dir }}
